openapi: 3.0.0
# Added by API Auto Mocking Plugin
info:
  description: Lark server api.
  version: "1.0.0"
  title: Lark
tags:
  - name: users
    description: user reqs.
paths:
  /auth:
    post:
      tags:
        - users
      summary: auth identity.
      operationId: authIdent
      description: Adds an item to the system
      responses:
        '200':
          description: "return uuid."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UUID'
        '400':
          description: 'invalid public key'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auth'
        description: Inventory item to add
  /{name}:
    get:
      tags: 
        - users
      summary: user info
      parameters:
        - name: name
          in: path
          description: User ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: return user info
components:
  schemas:
    Auth:
      type: object
      required: 
        - name
        - public_key
      properties:
        name:
          type: string
          example: "david-bowie"
        public_key:
          type: string
          example: "475349a9b3daf719bf2d21f46f958dc769c6a8eba103c7c72bdf697e04cecc23"
    UUID:
      type: object
      required: 
        - uuid
      properties:
        uuid:
          type: string
          example: "936DA01F9ABD4d9d80C702AF85C822A8"
        session_rand:
          type: string
          example: "35fcca1799c0d9d9cf0b6a6a0bebb19fb9d62a25ef972db832bb8cbdd31432bd"